services:
  dipoll:
    image: dipoll:latest
    container_name: pro-scheduler-mtg-fr
    restart: unless-stopped
    build:
      context: .
    environment:
      # Basics for the bot to work
      ROLE_ID: ${ROLE_ID}
      CHANNEL_ID: ${CHANNEL_ID}
      BOT_OWNER_ID: ${BOT_OWNER_ID}
      TOKEN: ${TOKEN}
      NOTIFY: ${NOTIFY}
      # Commands customization
      PREFIX_CMD: "_mtg"
      FORCE_SCHEDULE_CMD: "_force"
      ENABLE_SCHEDULER_CMD: "_enable"
      DISABLE_SCHEDULER_CMD: "_disable"
      # Emote declaration
      YES_EMOTE: "\U00002705"
      NO_EMOTE: "\U0000274C"
      WARN_EMOTE: "\U000026A0"
      # Schedule, answers and duration for the poll
      SCHEDULES: "1-2000"
      POLL_DURATION_HOURS: 89
      POLL_ANSWERS: "5-13h30_14h00,6-13h30_14h00"
      # Localization
      ACTIVITY_TEXT: "Magic: The Sect"
      POLL_TITLE_TEXT: "MTG - Prochaine session de jeu"
      POLL_AWAY_TEXT: "Absent"
      POLL_BETWEEN_TEXT: "entre"
      POLL_AND_TEXT: "et"
      POLL_AT_TEXT: "à"
      MONDAY_TEXT: "Lundi"
      TUESDAY_TEXT: "Mardi"
      WEDNESDAY_TEXT: "Mercredi"
      THURSDAY_TEXT: "Jeudi"
      FRIDAY_TEXT: "Vendredi"
      SATURDAY_TEXT: "Samedi"
      SUNDAY_TEXT: "Dimanche"