version: "3.9"

services:
  dipoll:
    image: dipoll:1.0.0
    container_name: default-scheduler
    restart: unless-stopped
    environment:
      # Basics for the bot to work
      ROLE_ID: ${ROLE_ID}
      CHANNEL_ID: ${CHANNEL_ID}
      BOT_OWNER_ID: ${BOT_OWNER_ID}
      TOKEN: ${TOKEN}
      NOTIFY: ${NOTIFY}